
FIELD_TYPES = {
    "string": {
        "formType": "text",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "text",
        "testValue": '"Sample text"',
        "updateValue": '"Updated sample text"',
        "col": 6,
    },
    "url": {
        "formType": "text",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "text",
        "testValue": '"https://example.com"',
        "updateValue": '"https://updated.example.com"',
        "col": 6,
    },
    "number": {
        "formType": "number",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "number",
        "testValue": "42",
        "updateValue": "52",
        "col": 6,
    },
    "integer": {
        "formType": "number",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "number",
        "testValue": "100",
        "updateValue": "200",
        "col": 6,
    },
    "decimal": {
        "formType": "number",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "number",
        "testValue": "10.50",
        "updateValue": "20.75",
        "col": 6,
    },
    "boolean": {
        "formType": "checkbox",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "boolean",
        "testValue": "true",
        "updateValue": "false",
        "col": 6,
    },
    "checkbox": {
        "formType": "checkbox",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "boolean",
        "testValue": "true",
        "updateValue": "false",
        "col": 6,
    },
    "image": {
        "formType": "file",
        "validation": "nullable",
        "updateValidation": "nullable",
        "tableDisplay": "image",
        "testValue": "null",
        "updateValue": "null",
        "col": 12,
    },
    "textarea": {
        "formType": "textarea",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "text",
        "testValue": '"Long text content"',
        "updateValue": '"Updated long text content"',
        "col": 12,
    },
    "json": {
        "formType": "textarea",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "text",
        "testValue": '\'{"key": "value"}\'',
        "updateValue": '\'{"key": "new_value"}\'',
        "col": 12,
    },
    "text": {
        "formType": "textarea",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "text",
        "testValue": '"Long text content"',
        "updateValue": '"Updated long text content"',
        "col": 12,
    },
    "email": {
        "formType": "email",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "text",
        "testValue": '"test@example.com"',
        "updateValue": '"updated@example.com"',
        "col": 6,
    },
    "password": {
        "formType": "password",
        "validation": "required",
        "updateValidation": "nullable",
        "tableDisplay": "hidden",
        "testValue": '"password123"',
        "updateValue": '"newpassword123"',
        "col": 6,
    },
    "date": {
        "formType": "date",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "date",
        "testValue": '"2023-01-01"',
        "updateValue": '"2023-12-31"',
        "col": 6,
    },
    "datetime": {
        "formType": "datetime-local",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "date",
        "testValue": '"2023-01-01T12:00"',
        "updateValue": '"2023-12-31T12:00"',
        "col": 6,
    },
    "select": {
        "formType": "select",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "text",
        "hasOptions": True,
        "testValue": '"option1"',
        "updateValue": '"option2"',
        "col": 6,
    },
    "enum": {
        "formType": "select",
        "validation": "required",
        "updateValidation": "required",
        "tableDisplay": "text",
        "hasOptions": True,
        "testValue": '"option1"',
        "updateValue": '"option2"',
        "col": 6,
    }
}

RELATIONSHIP_TYPES = {
    "belongsTo": {
        "method": "belongsTo",
        "inverse": "hasMany",
        "supported": True,
    },
    "hasOne": {
        "method": "hasOne",
        "inverse": "belongsTo",
        "supported": True,
    },
    "hasMany": {
        "method": "hasMany",
        "inverse": "belongsTo",
        "supported": True,
    },
    "belongsToMany": {
        "method": "belongsToMany",
        "inverse": "belongsToMany",
        "supported": True,
    },
}